
hello_the_world:
    path: /hello_world
    defaults: { _controller: OCPlatformBundle:Advert:index}

byebye-world:
    path: /byebye_world
    defaults: { _controller: OCPlatformBundle:Advert:byebye}
